from django.urls import path

from . import (
    audit_views,
    book_export_views,
    document_views,
    enhancement_views,
    import_views,
    list_views,
    masterdata_views,
    periodic_reports,
    phase9_views,
    report_views,
    views,
)

app_name = "inventory"

urlpatterns = [
    path("change-temporary-password/", views.change_temporary_password, name="change_temporary_password"),
    path("", views.dashboard, name="dashboard"),
    path("search/employees/", phase9_views.employee_autocomplete, name="employee_autocomplete"),
    path("search/tshirt-stock/", phase9_views.tshirt_stock_autocomplete, name="tshirt_stock_autocomplete"),
    path("books/", list_views.book_list, name="book_list"),
    path("books/add/", views.book_create, name="book_create"),
    path("books/<int:pk>/edit/", views.book_edit, name="book_edit"),
    path("books/<int:pk>/details/", phase9_views.book_detail, name="book_detail"),
    path("books/<int:pk>/documents/<str:document_type>/", document_views.book_document, name="book_document"),
    path("books/history/", list_views.book_history, name="book_history"),
    path("books/<int:pk>/label/", views.book_asset_label, name="book_asset_label"),
    path("books/<int:pk>/allocate/", phase9_views.book_allocate, name="book_allocate"),
    path("book-allocations/<int:pk>/return/", phase9_views.book_return, name="book_return"),
    path("books/<int:pk>/delete/", views.book_delete, name="book_delete"),
    path("employees/", list_views.employee_list, name="employee_list"),
    path("employees/add/", phase9_views.employee_create, name="employee_create"),
    path("employees/add-without-login/", phase9_views.employee_create, name="employee_record_create"),
    path("employees/<int:pk>/history/", list_views.employee_history, name="employee_history"),
    path("employees/<int:pk>/history.xlsx", report_views.export_employee_history_excel, name="export_employee_history_excel"),
    path("employees/<int:pk>/edit/", phase9_views.employee_edit, name="employee_edit"),
    path("employees/<int:pk>/delete/", masterdata_views.employee_delete, name="employee_delete"),
    path("login-users/", list_views.login_user_list, name="login_user_list"),
    path("login-users/add/", views.login_user_create, name="login_user_create"),
    path("login-users/<int:pk>/edit/", views.login_user_edit, name="login_user_edit"),
    path("login-users/<int:pk>/reset-password/", views.employee_reset_password, name="employee_reset_password"),
    path("login-users/<int:pk>/delete/", masterdata_views.login_user_delete, name="login_user_delete"),
    path("tshirts/brands/", list_views.tshirt_brand_list, name="tshirt_brand_list"),
    path("tshirts/brands/add/", enhancement_views.tshirt_brand_create, name="tshirt_brand_create"),
    path("tshirts/brands/<int:pk>/edit/", enhancement_views.tshirt_brand_edit, name="tshirt_brand_edit"),
    path("tshirts/brands/<int:pk>/deactivate/", enhancement_views.tshirt_brand_deactivate, name="tshirt_brand_deactivate"),
    path("tshirts/stock/", list_views.tshirt_stock_list, name="tshirt_stock_list"),
    path("tshirts/stock/<int:pk>/threshold/", enhancement_views.tshirt_stock_threshold_edit, name="tshirt_stock_threshold_edit"),
    path("tshirts/stock/<int:pk>/correct/", phase9_views.tshirt_stock_correct, name="tshirt_stock_correct"),
    path("tshirts/purchases/add/", views.tshirt_purchase_create, name="tshirt_purchase_create"),
    path("tshirts/purchases/<int:pk>/bill/", document_views.tshirt_purchase_document, name="tshirt_purchase_document"),
    path("tshirts/issue-free/", phase9_views.free_tshirt_issue, name="free_tshirt_issue"),
    path("tshirts/request-paid/", phase9_views.paid_tshirt_request, name="paid_tshirt_request"),
    path("tshirts/allocations/", list_views.tshirt_allocation_list, name="tshirt_allocation_list"),
    path("tshirts/allocations/<int:pk>/review/", phase9_views.paid_tshirt_review, name="paid_tshirt_review"),
    path("tshirts/allocations/<int:pk>/documents/<str:document_type>/", document_views.paid_tshirt_document, name="paid_tshirt_document"),
    path("tshirts/allocations/<int:pk>/approve/", views.paid_tshirt_approve, name="paid_tshirt_approve"),
    path("tshirts/allocations/<int:pk>/reject/", views.paid_tshirt_reject, name="paid_tshirt_reject"),
    path("imports/", import_views.bulk_import, name="bulk_import"),
    path("imports/templates/<str:import_type>/", import_views.download_import_template, name="download_import_template"),
    path("settings/branding/", views.branding_settings, name="branding"),
    path("reports/", views.reports_index, name="reports"),
    path("reports/activity/download/", periodic_reports.download_activity_report, name="download_activity_report"),
    path("reports/audit-evidence/", audit_views.audit_evidence_register, name="audit_evidence_register"),
    path("reports/audit-evidence/export/", audit_views.audit_evidence_export, name="audit_evidence_export"),
    path("backups/download/", views.download_database_backup, name="download_database_backup"),
    path("reports/books.xlsx", book_export_views.export_books_excel, name="export_books_excel"),
    path("reports/books.pdf", book_export_views.export_books_pdf, name="export_books_pdf"),
    path("reports/tshirts.xlsx", views.export_tshirts_excel, name="export_tshirts_excel"),
    path("reports/employees.xlsx", report_views.export_employees_excel, name="export_employees_excel"),
    path("reports/book-history.xlsx", report_views.export_book_history_excel, name="export_book_history_excel"),
    path("reports/book-history.pdf", report_views.export_book_history_pdf, name="export_book_history_pdf"),
    path("reports/tshirt-history.xlsx", report_views.export_tshirt_allocations_excel, name="export_tshirt_allocations_excel"),
    path("reports/tshirt-stock.pdf", report_views.export_tshirt_stock_pdf, name="export_tshirt_stock_pdf"),
    path("reports/low-stock.xlsx", report_views.export_low_stock_excel, name="export_low_stock_excel"),
    path("reports/audit.xlsx", report_views.export_audit_excel, name="export_audit_excel"),
]
