from django.urls import path

from . import enhancement_views, import_views, list_views, masterdata_views, periodic_reports, report_views, views

app_name = "inventory"

urlpatterns = [
    path("change-temporary-password/", views.change_temporary_password, name="change_temporary_password"),
    path("", views.dashboard, name="dashboard"),
    path("books/", list_views.book_list, name="book_list"),
    path("books/add/", views.book_create, name="book_create"),
    path("books/<int:pk>/edit/", views.book_edit, name="book_edit"),
    path("books/history/", list_views.book_history, name="book_history"),
    path("books/<int:pk>/label/", views.book_asset_label, name="book_asset_label"),
    path("books/<int:pk>/allocate/", views.book_allocate_view, name="book_allocate"),
    path("book-allocations/<int:pk>/return/", views.book_return_view, name="book_return"),
    path("books/<int:pk>/delete/", views.book_delete, name="book_delete"),
    path("employees/", list_views.employee_list, name="employee_list"),
    path("employees/add/", views.employee_create, name="employee_create"),
    path("employees/add-without-login/", enhancement_views.employee_record_create, name="employee_record_create"),
    path("employees/<int:pk>/history/", list_views.employee_history, name="employee_history"),
    path("employees/<int:pk>/history.xlsx", report_views.export_employee_history_excel, name="export_employee_history_excel"),
    path("employees/<int:pk>/edit/", views.employee_edit, name="employee_edit"),
    path("employees/<int:pk>/delete/", masterdata_views.employee_delete, name="employee_delete"),
    path("login-users/", list_views.login_user_list, name="login_user_list"),
    path("login-users/add/", views.login_user_create, name="login_user_create"),
    path("login-users/<int:pk>/edit/", views.login_user_edit, name="login_user_edit"),
    path("login-users/<int:pk>/reset-password/", views.employee_reset_password, name="employee_reset_password"),
    path("login-users/<int:pk>/delete/", masterdata_views.login_user_delete, name="login_user_delete"),
    path("tshirts/brands/", list_views.tshirt_brand_list, name="tshirt_brand_list"),
    path("tshirts/brands/add/", enhancement_views.tshirt_brand_create, name="tshirt_brand_create"),
    path("tshirts/brands/<int:pk>/edit/", enhancement_views.tshirt_brand_edit, name="tshirt_brand_edit"),
    path("tshirts/brands/<int:pk>/deactivate/", enhancement_views.tshirt_brand_deactivate, name="tshirt_brand_deactivate"),
    path("tshirts/stock/", list_views.tshirt_stock_list, name="tshirt_stock_list"),
    path("tshirts/stock/<int:pk>/threshold/", enhancement_views.tshirt_stock_threshold_edit, name="tshirt_stock_threshold_edit"),
    path("tshirts/purchases/add/", views.tshirt_purchase_create, name="tshirt_purchase_create"),
    path("tshirts/issue-free/", views.free_tshirt_issue, name="free_tshirt_issue"),
    path("tshirts/request-paid/", views.paid_tshirt_request, name="paid_tshirt_request"),
    path("tshirts/allocations/", list_views.tshirt_allocation_list, name="tshirt_allocation_list"),
    path("tshirts/allocations/<int:pk>/approve/", views.paid_tshirt_approve, name="paid_tshirt_approve"),
    path("tshirts/allocations/<int:pk>/reject/", views.paid_tshirt_reject, name="paid_tshirt_reject"),
    path("imports/", import_views.bulk_import, name="bulk_import"),
    path("imports/templates/<str:import_type>/", import_views.download_import_template, name="download_import_template"),
    path("settings/branding/", views.branding_settings, name="branding"),
    path("reports/", views.reports_index, name="reports"),
    path("reports/activity/download/", periodic_reports.download_activity_report, name="download_activity_report"),
    path("backups/download/", views.download_database_backup, name="download_database_backup"),
    path("reports/books.xlsx", views.export_books_excel, name="export_books_excel"),
    path("reports/books.pdf", views.export_books_pdf, name="export_books_pdf"),
    path("reports/tshirts.xlsx", views.export_tshirts_excel, name="export_tshirts_excel"),
    path("reports/employees.xlsx", report_views.export_employees_excel, name="export_employees_excel"),
    path("reports/book-history.xlsx", report_views.export_book_history_excel, name="export_book_history_excel"),
    path("reports/book-history.pdf", report_views.export_book_history_pdf, name="export_book_history_pdf"),
    path("reports/tshirt-history.xlsx", report_views.export_tshirt_allocations_excel, name="export_tshirt_allocations_excel"),
    path("reports/tshirt-stock.pdf", report_views.export_tshirt_stock_pdf, name="export_tshirt_stock_pdf"),
    path("reports/low-stock.xlsx", report_views.export_low_stock_excel, name="export_low_stock_excel"),
    path("reports/audit.xlsx", report_views.export_audit_excel, name="export_audit_excel"),
]
