# Generated by Django 5.1.7 on 2026-07-22 10:13

import django.db.models.deletion
import django.utils.timezone
import inventory.managers
import inventory.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(default='Next Toppers', max_length=180)),
                ('app_logo', models.ImageField(blank=True, upload_to='branding/')),
                ('login_background', models.ImageField(blank=True, upload_to='branding/')),
                ('home_image', models.ImageField(blank=True, upload_to='branding/')),
                ('organization_picture', models.ImageField(blank=True, upload_to='branding/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TshirtBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('free_quantity_rolling_12_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(max_length=9, unique=True, validators=[inventory.validators.validate_employee_id])),
                ('full_name', models.CharField(max_length=180)),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[inventory.validators.validate_indian_mobile])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=160)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('default_tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=5)),
                ('must_change_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', inventory.managers.EmployeeManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_id', models.CharField(blank=True, max_length=10, unique=True, validators=[inventory.validators.validate_book_asset_id])),
                ('name', models.CharField(max_length=240)),
                ('class_name', models.CharField(blank=True, max_length=80)),
                ('stream_name', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_photo', models.ImageField(blank=True, upload_to='book_bills/')),
                ('book_photo', models.ImageField(blank=True, upload_to='books/')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='GOOD', max_length=20)),
                ('status', models.CharField(choices=[('IN_LIBRARY', 'In Library'), ('ALLOCATED', 'Allocated'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='IN_LIBRARY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='BookAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20)),
                ('return_note', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.book')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_allocations', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_returns_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('GOOGLE_CHAT', 'Google Chat')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TshirtStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.tshirtbrand')),
            ],
            options={
                'ordering': ['brand__name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='TshirtPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor', models.CharField(blank=True, max_length=180)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_photo', models.ImageField(blank=True, upload_to='tshirt_bills/')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tshirt_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.tshirtstock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TshirtAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issue_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued')], default='PENDING', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_proof', models.FileField(blank=True, upload_to='payment_proofs/')),
                ('hr_approval_proof', models.FileField(blank=True, upload_to='hr_approvals/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tshirt_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tshirt_allocations', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tshirts_issued', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tshirt_requests_created', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.tshirtstock')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name', 'class_name', 'stream_name'], name='inventory_b_name_616d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('book',), name='one_active_allocation_per_book'),
        ),
        migrations.AddConstraint(
            model_name='tshirtstock',
            constraint=models.UniqueConstraint(fields=('brand', 'size'), name='unique_brand_size_stock'),
        ),
    ]
