# Generated by Django 5.1.7 on 2026-07-22 12:15

import django.db.models.deletion
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tshirtbrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bookallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_book_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tshirtallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_tshirt_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='login_users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Data Entry User')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=9, unique=True, validators=[inventory.validators.validate_employee_id])),
                ('full_name', models.CharField(max_length=180)),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[inventory.validators.validate_indian_mobile])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=160)),
                ('profile_picture', models.ImageField(blank=True, upload_to='employees/')),
                ('default_tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['full_name', 'mobile_number'], name='inventory_e_full_na_22d7da_idx')],
            },
        ),
        migrations.AddField(
            model_name='bookallocation',
            name='employee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_allocations', to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='employee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='tshirtallocation',
            name='employee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tshirt_allocations', to='inventory.employee'),
        ),
    ]
