# Generated by Django 5.1.7 on 2026-07-23 13:27

import inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_tshirtbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[inventory.validators.validate_indian_mobile]),
        ),
    ]
