# Generated by Django 5.1.7 on 2026-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_book_publication_name_book_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tshirt_entitlement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tshirt_entitlement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
